#!/usr/bin/env node
/**
 * openai-tailor.mjs — OpenAI-compatible CV Tailoring for career-ops
 *
 * Stable root facade. Tailoring logic lives in lib/evaluation/tailor.mjs.
 */

import { existsSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import { runTailoring } from './lib/evaluation/tailor.mjs';
import { loadDotenvOptional } from './lib/evaluation/cli-args.mjs';
import { assertHostedOpenAiEndpoint, parseTimeoutMs } from './lib/evaluation/guards.mjs';

export { buildSystemMessage } from './lib/evaluation/index.mjs';

const ROOT = dirname(fileURLToPath(import.meta.url));

function printHelp() {
  console.log(`
╔══════════════════════════════════════════════════════════════════╗
║      career-ops — OpenAI-compatible CV Tailoring (Headless)      ║
╚══════════════════════════════════════════════════════════════════╝

  Tailor your CV with any OpenAI-compatible API to output a filled HTML file.

  USAGE
    node openai-tailor.mjs --jd <path> --report <path>
    node openai-tailor.mjs --url <base> --model <id> --jd <path> --report <path>

  OPTIONS
    --jd <path>      Path to the Job Description text file
    --report <path>  Path to the evaluation report generated by openai-eval.mjs
    --model <id>     Model id            (env OPENAI_MODEL, default gpt-4o)
    --url <base>     OpenAI-compatible base URL, including any /v1
                     (env OPENAI_BASE_URL, default https://api.openai.com/v1)
    --key <key>      API key             (env OPENAI_API_KEY)
    --help           Show this help

  ENV
    OPENAI_API_KEY, OPENAI_BASE_URL, OPENAI_MODEL, OPENAI_TIMEOUT_MS
`);
}

const invokedDirectly = process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  await loadDotenvOptional();

  const args = process.argv.slice(2);
  if (args.length === 0 || args[0] === '--help' || args[0] === '-h') {
    printHelp();
    process.exit(0);
  }

  let jdPath = '';
  let reportPath = '';
  let modelName = process.env.OPENAI_MODEL || 'gpt-4o';
  let baseUrl = (process.env.OPENAI_BASE_URL || 'https://api.openai.com/v1').replace(/\/$/, '');
  let apiKey = process.env.OPENAI_API_KEY || '';

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--jd' && args[i + 1]) jdPath = args[++i];
    else if (args[i] === '--report' && args[i + 1]) reportPath = args[++i];
    else if (args[i] === '--model' && args[i + 1]) modelName = args[++i];
    else if (args[i] === '--url' && args[i + 1]) baseUrl = args[++i].replace(/\/$/, '');
    else if (args[i] === '--key' && args[i + 1]) apiKey = args[++i];
  }

  if (!jdPath || !reportPath) {
    console.error('❌  Both --jd and --report are required. Run with --help for usage.');
    process.exit(1);
  }
  if (!existsSync(jdPath)) {
    console.error(`❌  JD file not found: ${jdPath}`);
    process.exit(1);
  }
  if (!existsSync(reportPath)) {
    console.error(`❌  Report file not found: ${reportPath}`);
    process.exit(1);
  }

  try {
    assertHostedOpenAiEndpoint({ baseUrl, apiKey });
    parseTimeoutMs(process.env.OPENAI_TIMEOUT_MS);
    await runTailoring({ rootDir: ROOT, jdPath, reportPath, modelName, baseUrl, apiKey });
  } catch (err) {
    console.error(`❌  ${err.message}`);
    process.exit(1);
  }
}
