package data

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
)

type trackerContract struct {
	ContractVersion      int               `json:"contractVersion"`
	HeaderAliases        map[string]string `json:"headerAliases"`
	LegacyColumnMap      map[string]int    `json:"legacyColumnMap"`
	RequiredHeaderFields []string          `json:"requiredHeaderFields"`
	States               []trackerState    `json:"states"`
}

type trackerState struct {
	ID      string   `json:"id"`
	Label   string   `json:"label"`
	Aliases []string `json:"aliases"`
}

var (
	contractOnce sync.Once
	contractData trackerContract
	contractErr  error
)

func trackerContractPath() string {
	if override := os.Getenv("CAREER_OPS_SYSTEM_ROOT"); override != "" {
		return filepath.Join(override, "templates", "tracker-contract.json")
	}
	_, filename, _, ok := runtime.Caller(0)
	if ok {
		return filepath.Clean(filepath.Join(filepath.Dir(filename), "..", "..", "..", "templates", "tracker-contract.json"))
	}
	return filepath.Join("templates", "tracker-contract.json")
}

func loadTrackerContract() (trackerContract, error) {
	contractOnce.Do(func() {
		raw, err := os.ReadFile(trackerContractPath())
		if err != nil {
			contractErr = fmt.Errorf("read tracker contract: %w", err)
			return
		}
		contractErr = json.Unmarshal(raw, &contractData)
	})
	return contractData, contractErr
}

// TrackerHeaderAliases returns the canonical header alias map from
// templates/tracker-contract.json (generated by lib/tracker/contract.mjs).
func TrackerHeaderAliases() (map[string]string, error) {
	c, err := loadTrackerContract()
	if err != nil {
		return nil, err
	}
	out := make(map[string]string, len(c.HeaderAliases))
	for k, v := range c.HeaderAliases {
		out[k] = v
	}
	return out, nil
}

// TrackerRequiredHeaderFields returns required columns from the contract artifact.
func TrackerRequiredHeaderFields() ([]string, error) {
	c, err := loadTrackerContract()
	if err != nil {
		return nil, err
	}
	return append([]string(nil), c.RequiredHeaderFields...), nil
}

// TrackerCanonicalStates returns canonical state labels from the contract artifact.
func TrackerCanonicalStates() ([]string, error) {
	c, err := loadTrackerContract()
	if err != nil {
		return nil, err
	}
	labels := make([]string, 0, len(c.States))
	for _, s := range c.States {
		labels = append(labels, s.Label)
	}
	return labels, nil
}

// ResolveTrackerStateLabel maps a label or alias to the canonical label.
func ResolveTrackerStateLabel(input string) (string, error) {
	c, err := loadTrackerContract()
	if err != nil {
		return "", err
	}
	want := strings.TrimSpace(input)
	for _, s := range c.States {
		if strings.EqualFold(s.Label, want) {
			return s.Label, nil
		}
		for _, alias := range s.Aliases {
			if strings.EqualFold(alias, want) {
				return s.Label, nil
			}
		}
	}
	return "", fmt.Errorf("non-canonical state: %q", input)
}
